name: Maven Build with Docker

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  PG_DB: soc_wallet_test_db


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yml"
      - name: Build with Maven
        run:
          mvn clean package
